### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by mattvenn** [jonathan-nuvetech/BasicMOSFET3#4]
Hi! I showed this around to some ASIC engineers I know, and one gave this feedback:

That is really cool.  

I didn't run it yet but looking at the code it's using the Sze long channel model, which practically eveyone uses so I get it, but I never personally really liked much. 

So I'll do one short rant...

The problem is pinch-off is super confusing in Sze's model.    The charge in the inversion layer drops to zero and then you have to explain how current exists when there is no charge.  That violates the definition fairly directly so most people just waive their hands and go "modern physics".  And then you get to modern physics and they say, what are you talking about there's totally charge there.  See these nice band diagrams... Ugh.  And that's when people switch to CS. 

Chenming Hu's (inventor of FinFET) very good (and somehow free!) text starts with Sze's model, like everyone does so you have to know it, but then offers a much better alternative long channel model which doesn't have this whole loss of inversion layer charge problem.   (See 6.9)  I'm not going to retype it but instead of looking at the charge volume and how it changes across the channel under various fields, it looks at the charge velocity.   Then you just say charge has a top speed, which agrees totally with modern physics. 

Here is an excerpt from the text, "The situation is like a mountain stream feeding into a waterfall. The slope of the river bed (dEc/dx) and the amount of water in the stream determine the water flow rate in the stream, which in turn determines the flow rate down the waterfall. The height of the waterfall (Vds − Vdsat), whether 1 or 100 m, has no influence over the flow rate."

https://www.chu.berkeley.edu/modern-semiconductor-devices-for-integrated-circuits-chenming-calvin-hu-2010/

![image](https://github.com/jonathan-nuvetech/BasicMOSFET3/assets/634220/d45e80b1-9874-49db-9f35-33d57c355b5f)

**Comment by jonathan-nuvetech** [comment]
This is great feedback. In truth, the simulator is much worse than just assuming long channel - to make the transition between linear and saturation smooth, I had to make some even worse approximations. I also make some really big assumptions about the electric field and the charge carriers. A device physics engineer might cringe at the simulator.

But, the aim of the simulator is not to be accurate, or even true. Rather, it is aimed at helping students grasp that first concept of regions of operation, drift velocity, pinch-off (going from linear to saturation or vice versa), and just a general 3D image of what it looks like. I try to show this basic working without complicating it more for people who might be seeing this for their first or second time. 

Maybe one day I might be inspired enough to do a full metal physics simulator that tries to be as accurate as possible, but that might take a few years from now :)
